#### COMPANION WORKBOOK

# NumPy

To make the most out this program, we strongly recommend you to:
1. First practice writing and implementing all of the code from Coding Section of the online lesson.
2. Then, freely experiment with and explore any interesting or confusing concepts. Simply insert new code cells and then use the help of Google and official documentation.
3. Finally, tackle all of the exercises at the end. They will help you tie everything together and **learn in context.**

#### <span style="color:#555">LESSON CODE SANDBOX</span>

Use this space to practice writing and implementing all of the code from Coding Section of the online lesson. Insert new code cells as needed, and feel free to write notes to yourself in Markdown.

First, let's import the actual NumPy library.

In [2]:
import numpy as np

## I. NumPy Arrays are homogeneous.

In [4]:
# Array of ints
array_a = np.array([0, 1, 2, 3])

print ( array_a )
print ( type(array_a) )

[0 1 2 3]
<class 'numpy.ndarray'>


In [6]:
# Print data type of contaied elements
print( array_a.dtype )

int32


In [12]:
# Mixed array with 1 string and 2 integers
array_b = np.array(['four', 5, 6])

# Print elements in array_b
print( array_b )

['four' '5' '6']


In [18]:
print( array_a.shape )
print( array_b.shape )

(4,)
(3,)


In [20]:
# First element of array_a
print( array_a[0] )

# Last element of array_a
print( array_a[-1] )

0
3


In [22]:
# From second element of array_a up to the 4th
print( array_a[2:4] )

[2 3]


In [26]:
# Array with  missing values
array_with_missing_value = np.array([1.2, 8.8, 4.0, np.nan, 6.1])

# Print array
print( array_with_missing_value )

[1.2 8.8 4.  nan 6.1]


In [28]:
# Print array's dtype
print( array_with_missing_value.dtype )

float64


## II. NumPy Arrays are multidimensional.

In [36]:
array_c = np.array([[1, 2, 3], [4, 5, 6]])
print( array_c )
print( array_c.shape )
# Reshape to 3x3
print( array_c.reshape(3, 2) )
# Reshape to 1x6
print( array_c.reshape(1,6) )

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]


In [38]:
# Print number axes
print( len(array_c.reshape(1,6).shape) )

2


In [42]:
# Reshape and reduce axes
print( array_c.reshape(6,) )

# Flatten (reduce to 1 axis)
print( array_c.flatten() )

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [44]:
# Print number of axes
print( len(array_c.reshape(6,).shape) )
print( len(array_c.flatten().shape) )

1
1


In [48]:
# Transpose
print( array_c.transpose() )

[[1 4]
 [2 5]
 [3 6]]


In [52]:
# create a 3x3 array
array_d = np.array(range(1,10)).reshape(3,3)
print(array_d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
# Select first row
print( array_d[0, :] )

[1 2 3]


In [56]:
# Select second row
print( array_d[1, :])

[4 5 6]


In [58]:
# Select third column
print( array_d[:, 2])

[3 6 9]


In [60]:
# Select second column
print( array_d[:, 1])

[2 5 8]


In [62]:
# Select after second row and second column
print( array_d[1:, 1:] )

[[5 6]
 [8 9]]


## III. NumPy math is elementwise.

In [74]:
# 2x2 matrix of floats
x = np.array([[1.0, 2.0], [3.0, 4.0]])
print( x )

# 2x2 matrix of floats
y = np.array([[2.0, 5.0], [10.0, 3.0]])
print( y )

[[1. 2.]
 [3. 4.]]
[[ 2.  5.]
 [10.  3.]]


In [76]:
# Math between two arrays (Addition)
print ( x + y)

[[ 3.  7.]
 [13.  7.]]


In [80]:
# Subtraction
print( x - 2, '\n')

# Multiplication
print( x * 2, '\n')
    
# Division
print( x / 2, '\n')

# Modulo
print( x % 2 )

[[-1.  0.]
 [ 1.  2.]] 

[[2. 4.]
 [6. 8.]] 

[[0.5 1. ]
 [1.5 2. ]] 

[[1. 0.]
 [1. 0.]]


In [82]:
# Squared
print( np.power(x, 2), '\n' )

# Cubed
print( np.power(x, 3), '\n' )

# Natural Log
print( np.log(x), '\n' )

# Square Root
print( np.sqrt(x) )

[[ 1.  4.]
 [ 9. 16.]] 

[[ 1.  8.]
 [27. 64.]] 

[[0.         0.69314718]
 [1.09861229 1.38629436]] 

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [88]:
# Sum of all elements
print( np.sum(x) )

10.0


In [95]:
print( np.min(x) ) # Min
print( np.max(x) ) # Max
print( np.median(x) ) # Median
print( np.mean(x) ) # Mean

1.0
4.0
2.5
2.5


In [97]:
# Sum of each column
print( np.sum(x, axis=0) )

[4. 6.]


In [99]:
# Sum of each row
print( np.sum(x, axis=1) )

[3. 7.]


## IV. NumPy is reliably random.

In [ ]:
np.random.

In [101]:
# Randomly draw 64 samples from a uniform distribution from [0, 10]
sample = np.random.randint(low=0, high=10, size=64)

print( sample )

[6 3 7 0 5 5 6 9 8 9 7 3 6 1 0 0 5 8 0 0 4 4 5 0 5 6 4 9 3 9 0 0 9 9 0 6 3
 9 8 1 2 7 5 9 8 0 0 0 1 6 3 6 5 7 4 6 2 6 9 2 1 5 3 1]


In [103]:
# Reshape to 8x8 matrix
print( sample.reshape((8,8)) )

[[6 3 7 0 5 5 6 9]
 [8 9 7 3 6 1 0 0]
 [5 8 0 0 4 4 5 0]
 [5 6 4 9 3 9 0 0]
 [9 9 0 6 3 9 8 1]
 [2 7 5 9 8 0 0 0]
 [1 6 3 6 5 7 4 6]
 [2 6 9 2 1 5 3 1]]


In [107]:
# Randomly draw 8x8 samples from a uniform distribution from [0, 10)
generated_matrix = np.random.randint(0, 10, (8,8))
print( generated_matrix)

[[2 5 3 3 6 5 1 4]
 [6 8 8 1 3 6 1 5]
 [5 7 2 8 4 6 6 3]
 [2 0 8 1 6 5 8 4]
 [1 4 2 3 0 9 0 6]
 [2 1 2 3 2 2 2 0]
 [5 0 7 3 6 9 1 7]
 [2 4 6 6 4 3 1 6]]


In [109]:
# Run exact same code as above
generated_matrix = np.random.randint(0, 10, (8,8))
print( generated_matrix )

[[0 3 1 4 9 5 8 7]
 [7 8 1 3 5 5 5 1]
 [5 0 7 7 4 4 1 9]
 [7 5 5 8 1 5 8 6]
 [6 4 0 1 8 5 3 2]
 [9 6 4 1 0 1 6 0]
 [7 4 6 4 6 0 1 1]
 [3 8 8 9 3 0 2 6]]


In [111]:
# Run exact same code as above
generated_matrix = np.random.randint(0, 10, (8,8))
print( generated_matrix )

[[1 9 1 1 5 8 0 9]
 [2 3 4 6 4 7 3 6]
 [1 0 7 8 7 2 3 1]
 [4 7 0 9 7 4 3 9]
 [2 2 6 6 3 6 4 8]
 [5 6 3 4 7 5 1 4]
 [0 8 2 6 8 7 3 4]
 [5 4 9 3 5 0 2 5]]


In [113]:
# Set seed for reproducible results
np.random.seed(321)

# Randomly draw 4x4 samples from a uniform distribution from [0,10)
generated_matrix = np.random.randint(0, 10, (8,8))

print( generated_matrix )

[[4 9 8 1 8 8 4 5]
 [8 3 5 1 4 6 5 7]
 [7 2 2 3 9 2 1 2]
 [1 1 0 4 4 3 0 3]
 [7 4 5 7 0 8 7 1]
 [0 2 5 6 1 0 7 2]
 [8 3 0 3 9 8 5 6]
 [0 2 7 5 2 3 9 9]]


In [115]:
# Set seed for reproducible results
np.random.seed(321)

# Randomly draw 4x4 samples from a uniform distribution from [0,10)
generated_matrix = np.random.randint(0, 10, (8,8))

print( generated_matrix )

[[4 9 8 1 8 8 4 5]
 [8 3 5 1 4 6 5 7]
 [7 2 2 3 9 2 1 2]
 [1 1 0 4 4 3 0 3]
 [7 4 5 7 0 8 7 1]
 [0 2 5 6 1 0 7 2]
 [8 3 0 3 9 8 5 6]
 [0 2 7 5 2 3 9 9]]


In [117]:
# Select first column of generated_Matrix
print( generated_matrix[:, 0] )

[4 8 7 1 7 0 8 0]


In [121]:
# Set seed for reproducible results
np.random.seed(55)

# Randomly select 5 elements from first column of generated_matrix
print( np.random.choice(generated_matrix[:,0], 5) )

[0 7 0 4 0]


In [123]:
# Set seed for reproducible results
np.random.seed(55)

# Randomly select 5 elements from first column of generated_matrix
print( np.random.choice(generated_matrix[:,0], 5, replace=False) )

[7 0 8 8 1]


In [ ]:
# Randomly 
